### ISSUE TITLE
基于Attention的受关键词控制的文本生成模型 有没有开源的计划？

### ISSUE THREAD

**Issue by solderzzc** [hit-computer/char-rnn-tf#1]
读了您这篇文章，感觉非常好。不知是否会开源 ‘基于Attention的受关键词控制的文本生成模型’ ？

**Comment by hit-computer** [comment]
感谢您的关注。这个模型还在不断改进中，等取得了比较理想的效果后会开源的，谢谢啦

**Comment by hit-computer** [comment]
我们的方面和模型暂时还未开源，但如果对这一任务比较感兴趣的话，可以先参考一下我们已经实现的[SC-LSTM](https://github.com/hit-computer/SC-LSTM)模型。SC-LSTM是EMNLP) 2015一篇论文中的模型，也是做基于语义信息控制文本生成任务的，同样可以输入一组关键词然后生成和关键词语义相关的文本。谢谢啦 :)

**Comment by Anppy** [comment]
您好，对您基于Attention的受关键词控制的文本生成模型非常感兴趣，不知是以论文形式发表，还是会有开源代码？如果方便，可否介绍一下模型的基本思想，以便学习，另外，不知您所训练的作文数据集能否共享？非常感谢！

**Comment by hit-computer** [comment]
@Anppy 您好，原本我们是会公开数据和代码的，只可惜这部分实验投了今年的emnlp但却没有中，所有很遗憾目前暂时无法看到相关论文、代码以及数据。不过你可以参考[SC-LSTM](https://github.com/hit-computer/SC-LSTM)

**Comment by d5d** [comment]
会定时上来看看是否开源。很期待呀。 @hit-computer

**Comment by hit-computer** [comment]
@d5d 代码已经开源出来了；数据这部分百度云盘链接貌似失效了，我们近期会更新链接。
https://github.com/hit-computer/MTA-LSTM
