### ISSUE TITLE
关于run_echo()里的tf.no_op()

### ISSUE THREAD

**Issue by DrLai12club** [hit-computer/char-rnn-tf#13]
您好，请问为什么每次run_echo()的时候都要想graph里面塞一个no_op()的block呢？我没有太理解这个操作的理由。

我尝试将项目部署为在线服务，每次添加no_op()会导致graph越来越大，返回越来越慢。希望能解答，谢谢！

**Comment by hit-computer** [comment]
@DrLai12club  是为了使用统一的函数，但是没有考虑过 graph 会越来越大的问题。你可以根据自己的需求把这部分删掉

**Comment by DrLai12club** [comment]
好的谢谢 @hit-computer
